image: docker:19.03.2

variables:
  DOCKER_HOST: tcp://docker:2375
  CLUSTER_NAME: argo-wf
  REPO: thenatureofsoftware/argo-wf-runner

stages:
  - build
  - test
  - push

services:
  - docker:19.03.2-dind

buildDockerImage:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $REPO:rc .
    - echo "${DOCKER_PWD}" | docker login --username ${DOCKER_USER} --password-stdin
    - docker push $REPO:rc

testImage:
  image: ${REPO}:rc
  tags:
    - docker
  script:
    - ./scripts/run-argo-wf.sh https://raw.githubusercontent.com/argoproj/argo/master/examples/dag-diamond-steps.yaml

pushDockerImage:
  stage: push
  tags:
    - docker
  script:
    - VERSION="$(cat VERSION)"
    - docker pull $REPO:rc
    - docker tag $REPO:rc $REPO:$VERSION
    - echo "${DOCKER_PWD}" | docker login --username ${DOCKER_USER} --password-stdin
    - docker push $REPO:$VERSION
  only:
    refs:
      - master
