image: docker:19.03.2

variables:
  DOCKER_HOST: tcp://docker:2375
  AWR_WF_SERVICE: docker
  CLUSTER_NAME: argo-wf
  REPO: thenatureofsoftware/argo-wf-run

stages:
  - build
  - test
  - push

services:
  - docker:19.03.2-dind

buildDockerImage:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $REPO:rc .
    - echo "${DOCKER_PWD}" | docker login --username ${DOCKER_USER} --password-stdin
    - docker push $REPO:rc

testDagDiamondSteps:
  stage: test
  image: ${REPO}:rc
  tags:
    - docker
  script:
    - ./tests/testDagDiamondSteps.sh

testGlobalParameters:
  stage: test
  image: ${REPO}:rc
  tags:
    - docker
  variables:
    AWR_WF_PARAMETERS: message%3A%20Hello%20World%20from%20argo-wf-run%5Cn
  script:
    - ./tests/testGlobalParameters.sh

pushDockerImage:
  stage: push
  tags:
    - docker
  script:
    - VERSION="$(cat VERSION)"
    - docker pull $REPO:rc
    - docker tag $REPO:rc $REPO:$VERSION
    - echo "${DOCKER_PWD}" | docker login --username ${DOCKER_USER} --password-stdin
    - docker push $REPO:$VERSION
  only:
    refs:
      - master
